### ISSUE TITLE
we should add some api call here to show the real-time picks, could also be done as Zool poll or Mentimeter, but API is fancy -->

### ISSUE THREAD

**Issue by jensbri** [UoA-eResearch/ResBaz24Python#12]
https://github.com/UoA-eResearch/ResBaz24Python/blob/66f9329664404ec72af0679485972aed3a678ccd/IntroductionToPython.ipynb#L2

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by jensbri** [comment]
we went for API and it works great
